"""add knowledge base entities

Revision ID: 0ba39f226686
Revises: 
Create Date: 2026-07-06 15:17:24.647652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ba39f226686'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_code'), 'capability', ['code'], unique=True)
    op.create_table('framework',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_framework_name_version')
    )
    op.create_table('vendor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('headquarters', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_name'), 'vendor', ['name'], unique=True)
    op.create_table('framework_mapping',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('control_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('control_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['framework.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capability_id', 'framework_id', 'control_id', name='uq_mapping_capability_framework_control')
    )
    op.create_index(op.f('ix_framework_mapping_capability_id'), 'framework_mapping', ['capability_id'], unique=False)
    op.create_index(op.f('ix_framework_mapping_framework_id'), 'framework_mapping', ['framework_id'], unique=False)
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'name', name='uq_product_vendor_name')
    )
    op.create_index(op.f('ix_product_vendor_id'), 'product', ['vendor_id'], unique=False)
    op.create_table('edition',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_edition_product_name')
    )
    op.create_index(op.f('ix_edition_product_id'), 'edition', ['product_id'], unique=False)
    op.create_table('module',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'name', name='uq_module_edition_name')
    )
    op.create_index(op.f('ix_module_edition_id'), 'module', ['edition_id'], unique=False)
    op.create_table('module_capability_link',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'capability_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_capability_link')
    op.drop_index(op.f('ix_module_edition_id'), table_name='module')
    op.drop_table('module')
    op.drop_index(op.f('ix_edition_product_id'), table_name='edition')
    op.drop_table('edition')
    op.drop_index(op.f('ix_product_vendor_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_framework_mapping_framework_id'), table_name='framework_mapping')
    op.drop_index(op.f('ix_framework_mapping_capability_id'), table_name='framework_mapping')
    op.drop_table('framework_mapping')
    op.drop_index(op.f('ix_vendor_name'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_table('framework')
    op.drop_index(op.f('ix_capability_code'), table_name='capability')
    op.drop_table('capability')
    # ### end Alembic commands ###
