"""add is_business_critical to capability

Revision ID: 0f651c813b9a
Revises: 1f781de6d14c
Create Date: 2026-07-07 10:04:17.949841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f651c813b9a'
down_revision: Union[str, None] = '1f781de6d14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to false; dropped immediately
    # after so new inserts rely on the application-level default instead.
    op.add_column(
        'capability',
        sa.Column('is_business_critical', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('capability', 'is_business_critical', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capability', 'is_business_critical')
    # ### end Alembic commands ###
