"""add product capability mapping

Revision ID: 14068425bf45
Revises: de02d693802f
Create Date: 2026-07-07 07:55:26.331396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14068425bf45'
down_revision: Union[str, None] = 'de02d693802f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_capability_mapping',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('licensing_tier', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('supported_platforms', sa.JSON(), nullable=True),
    sa.Column('deployment_model', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('availability_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'capability_id', 'licensing_tier', 'deployment_model', name='uq_product_mapping_module_capability_tier_deployment')
    )
    op.create_index(op.f('ix_product_capability_mapping_capability_id'), 'product_capability_mapping', ['capability_id'], unique=False)
    op.create_index(op.f('ix_product_capability_mapping_edition_id'), 'product_capability_mapping', ['edition_id'], unique=False)
    op.create_index(op.f('ix_product_capability_mapping_module_id'), 'product_capability_mapping', ['module_id'], unique=False)
    op.create_index(op.f('ix_product_capability_mapping_product_id'), 'product_capability_mapping', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_capability_mapping_vendor_id'), 'product_capability_mapping', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_capability_mapping_vendor_id'), table_name='product_capability_mapping')
    op.drop_index(op.f('ix_product_capability_mapping_product_id'), table_name='product_capability_mapping')
    op.drop_index(op.f('ix_product_capability_mapping_module_id'), table_name='product_capability_mapping')
    op.drop_index(op.f('ix_product_capability_mapping_edition_id'), table_name='product_capability_mapping')
    op.drop_index(op.f('ix_product_capability_mapping_capability_id'), table_name='product_capability_mapping')
    op.drop_table('product_capability_mapping')
    # ### end Alembic commands ###
