"""add customer assessment workspace

Revision ID: 1f781de6d14c
Revises: 14068425bf45
Create Date: 2026-07-07 08:52:47.814226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f781de6d14c'
down_revision: Union[str, None] = '14068425bf45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('headquarters', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=True)
    op.create_table('assessment_project',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_completion_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'name', name='uq_assessment_project_customer_name')
    )
    op.create_index(op.f('ix_assessment_project_customer_id'), 'assessment_project', ['customer_id'], unique=False)
    op.create_table('business_unit',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'name', name='uq_business_unit_customer_name')
    )
    op.create_index(op.f('ix_business_unit_customer_id'), 'business_unit', ['customer_id'], unique=False)
    op.create_table('environment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('environment_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'name', name='uq_environment_customer_name')
    )
    op.create_index(op.f('ix_environment_customer_id'), 'environment', ['customer_id'], unique=False)
    op.create_table('product_assignment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('license_quantity', sa.Integer(), nullable=True),
    sa.Column('deployment_model', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('deployment_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_project_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_project_id'], ['assessment_project.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_project_id', 'edition_id', 'environment_id', name='uq_assignment_project_edition_environment')
    )
    op.create_index(op.f('ix_product_assignment_assessment_project_id'), 'product_assignment', ['assessment_project_id'], unique=False)
    op.create_index(op.f('ix_product_assignment_edition_id'), 'product_assignment', ['edition_id'], unique=False)
    op.create_index(op.f('ix_product_assignment_environment_id'), 'product_assignment', ['environment_id'], unique=False)
    op.create_index(op.f('ix_product_assignment_product_id'), 'product_assignment', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_assignment_vendor_id'), 'product_assignment', ['vendor_id'], unique=False)
    op.create_table('product_assignment_module_link',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['product_assignment.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('assignment_id', 'module_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_assignment_module_link')
    op.drop_index(op.f('ix_product_assignment_vendor_id'), table_name='product_assignment')
    op.drop_index(op.f('ix_product_assignment_product_id'), table_name='product_assignment')
    op.drop_index(op.f('ix_product_assignment_environment_id'), table_name='product_assignment')
    op.drop_index(op.f('ix_product_assignment_edition_id'), table_name='product_assignment')
    op.drop_index(op.f('ix_product_assignment_assessment_project_id'), table_name='product_assignment')
    op.drop_table('product_assignment')
    op.drop_index(op.f('ix_environment_customer_id'), table_name='environment')
    op.drop_table('environment')
    op.drop_index(op.f('ix_business_unit_customer_id'), table_name='business_unit')
    op.drop_table('business_unit')
    op.drop_index(op.f('ix_assessment_project_customer_id'), table_name='assessment_project')
    op.drop_table('assessment_project')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
