"""add simulation run

Revision ID: d7ebaf888994
Revises: 0f651c813b9a
Create Date: 2026-07-07 10:07:37.495779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7ebaf888994'
down_revision: Union[str, None] = '0f651c813b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_run',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('scenario_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('request_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_project_id'], ['assessment_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_run_assessment_project_id'), 'simulation_run', ['assessment_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_run_assessment_project_id'), table_name='simulation_run')
    op.drop_table('simulation_run')
    # ### end Alembic commands ###
